FROM clojure:lein

MAINTAINER Mateusz Probachta <mateusz.probachta@pragmaticcoders.com>

ENV NODE_VERSION v7.8.0
ENV NVM_DIR /usr/local/nvm

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get install build-essential -y &&\
    apt-get install curl -y &&\
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash && \
    source $NVM_DIR/nvm.sh &&\
    nvm install $NODE_VERSION &&\
    nvm alias default $NODE_VERSION &&\
    nvm use default;

EXPOSE 3000
EXPOSE 7000

RUN mkdir -p /app
ADD . /app
WORKDIR /app